# Generated by Django 3.2.12 on 2024-06-21 12:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RightCategory',
            fields=[
                ('category', models.SmallIntegerField(default=None, primary_key=True, serialize=False)),
                ('desc', models.CharField(default='Academics', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='RightDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('abbr', models.CharField(default='right_abbr', max_length=50)),
                ('details', models.CharField(default='right_description', max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rbac.rightcategory')),
            ],
        ),
        migrations.CreateModel(
            name='RightType',
            fields=[
                ('type', models.SmallIntegerField(default=None, primary_key=True, serialize=False)),
                ('desc', models.CharField(default='Master', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='UserRights',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('right', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rbac.rightdetails')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='rightdetails',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rbac.righttype'),
        ),
    ]
