# Generated by Django 3.2.12 on 2024-06-21 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('acayear', models.CharField(default='2020-21', max_length=8, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Admission_Quota',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='BloodGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=15, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='GM', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='CourseType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Coursetype', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dept_id', models.AutoField(primary_key=True, serialize=False)),
                ('dept_abbr', models.CharField(max_length=6)),
                ('dept_name', models.CharField(max_length=60)),
                ('start_year', models.DateField()),
                ('close_year', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('division', models.CharField(default='A', max_length=2, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExtValuatorCollegeName',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='GradeMapping',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('MinMarks', models.SmallIntegerField()),
                ('MaxMarks', models.SmallIntegerField()),
                ('GradePoints', models.SmallIntegerField()),
                ('Grade', models.CharField(max_length=1)),
                ('GradeScheme', models.SmallIntegerField()),
                ('TotalMarks', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Months',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=15, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Religion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.AutoField(primary_key=True, serialize=False)),
                ('room_name', models.CharField(max_length=10, null=True, unique=True)),
                ('row', models.SmallIntegerField(null=True)),
                ('column', models.SmallIntegerField(null=True)),
                ('Total_seats', models.SmallIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='States',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='Karnataka', max_length=60, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('usertype_id', models.SmallIntegerField(default=2)),
                ('usertype_name', models.CharField(max_length=20)),
            ],
        ),
    ]
