# Generated by Django 3.2.12 on 2024-07-25 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_mgmt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detained_type',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Detained_type', models.CharField(max_length=60, unique=True)),
            ],
        ),
    ]
