# Generated by Django 3.2.12 on 2024-06-21 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admission', '0001_initial'),
        ('master_mgmt', '__first__'),
        ('hr', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Academic_Calendar',
            fields=[
                ('acad_cal_id', models.AutoField(primary_key=True, serialize=False)),
                ('acad_cal_sem', models.SmallIntegerField(null=True)),
                ('acad_cal_induction_program_from', models.DateField(null=True)),
                ('acad_cal_induction_program_to', models.DateField(null=True)),
                ('acad_cal_teaching_commences', models.DateField(null=True)),
                ('acad_cal_reg_date_from', models.DateField(null=True)),
                ('acad_cal_reg_date_to', models.DateField(null=True)),
                ('acad_cal_reg_last_date_fee', models.DateField(null=True)),
                ('acad_cal_att_display_ia_1', models.DateField(null=True)),
                ('acad_cal_ia_1_from', models.DateField(null=True)),
                ('acad_cal_ia_1_to', models.DateField(null=True)),
                ('acad_cal_commn_to_parent_ia_1', models.DateField(null=True)),
                ('acad_cal_drop_course', models.DateField(null=True)),
                ('acad_cal_att_display_ia_2', models.DateField(null=True)),
                ('acad_cal_ia_2_from', models.DateField(null=True)),
                ('acad_cal_ia_2_to', models.DateField(null=True)),
                ('acad_cal_commn_to_parent_ia_2', models.DateField(null=True)),
                ('acad_cal_withdraw_course', models.DateField(null=True)),
                ('acad_cal_parents_meet', models.DateField(null=True)),
                ('acad_cal_st_feedback_from', models.DateField(null=True)),
                ('acad_cal_st_feedback_to', models.DateField(null=True)),
                ('acad_cal_ia_3_from', models.DateField(null=True)),
                ('acad_cal_ia_3_to', models.DateField(null=True)),
                ('acad_cal_last_day_teaching', models.DateField(null=True)),
                ('acad_cal_see_lab_from', models.DateField(null=True)),
                ('acad_cal_see_lab_to', models.DateField(null=True)),
                ('acad_cal_cie_marks_display', models.DateField(null=True)),
                ('acad_cal_attendance_display', models.DateField(null=True)),
                ('acad_cal_commn_to_parent_cie', models.DateField(null=True)),
                ('acad_cal_see_theory_from', models.DateField(null=True)),
                ('acad_cal_see_theory_to', models.DateField(null=True)),
                ('acad_cal_intersem_recess_from', models.DateField(null=True)),
                ('acad_cal_intersem_recess_to', models.DateField(null=True)),
                ('acad_cal_results_declaration', models.DateField(null=True)),
                ('acad_cal_makeup_from', models.DateField(null=True)),
                ('acad_cal_makeup_to', models.DateField(null=True)),
                ('acad_cal_acad_year', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='master_mgmt.academicyear')),
            ],
            options={
                'unique_together': {('acad_cal_acad_year', 'acad_cal_sem')},
            },
        ),
        migrations.CreateModel(
            name='Course_Outcome',
            fields=[
                ('co_num', models.SmallIntegerField(default=None, primary_key=True, serialize=False)),
                ('co_name', models.CharField(max_length=3, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback_Questionnaire',
            fields=[
                ('feedback_que_id', models.AutoField(primary_key=True, serialize=False)),
                ('feedback_que_no', models.IntegerField()),
                ('feedback_que_desc', models.CharField(max_length=100)),
                ('feedback_course_type', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Scheme_Details',
            fields=[
                ('scheme_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_code', models.CharField(max_length=15, unique=True)),
                ('course_title', models.CharField(max_length=50)),
                ('credits', models.SmallIntegerField(default=1)),
                ('ltps', models.CharField(max_length=8)),
                ('course_type', models.CharField(max_length=10)),
                ('sem_allotted', models.SmallIntegerField(default=1)),
                ('is_credit', models.BooleanField(default=False, null=True)),
                ('scheme_series', models.SmallIntegerField(default=1)),
                ('max_cie_marks', models.SmallIntegerField(default=50)),
                ('min_cie_marks', models.SmallIntegerField(default=20)),
                ('max_see_marks', models.SmallIntegerField(default=50, null=True)),
                ('min_see_marks', models.SmallIntegerField(default=20, null=True)),
                ('min_total_pass_marks', models.SmallIntegerField(default=40)),
                ('max_total_marks', models.SmallIntegerField(default=100)),
                ('deduction', models.SmallIntegerField(default=0, null=True)),
                ('program', models.SmallIntegerField(default=0, null=True)),
                ('open', models.SmallIntegerField(default=0, null=True)),
                ('offered_by', models.ForeignKey(db_column='offered_by', on_delete=django.db.models.deletion.CASCADE, to='master_mgmt.department')),
            ],
        ),
        migrations.CreateModel(
            name='Student_Division_Allotment',
            fields=[
                ('div_allot_id', models.AutoField(primary_key=True, serialize=False)),
                ('acad_cal_id', models.ForeignKey(db_column='acad_cal_id', on_delete=django.db.models.deletion.CASCADE, to='academics.academic_calendar')),
                ('dept', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='master_mgmt.department')),
                ('division', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='master_mgmt.division')),
                ('st_uid', models.ForeignKey(db_column='st_uid', on_delete=django.db.models.deletion.CASCADE, to='admission.student_details', to_field='st_uid')),
            ],
            options={
                'unique_together': {('acad_cal_id', 'st_uid')},
            },
        ),
        migrations.CreateModel(
            name='Student_current_status',
            fields=[
                ('st_id', models.AutoField(primary_key=True, serialize=False)),
                ('semester', models.SmallIntegerField(null=True)),
                ('total_credits_earned', models.SmallIntegerField(null=True)),
                ('cgpa', models.FloatField(blank=True, null=True)),
                ('sgpa', models.FloatField(blank=True, null=True)),
                ('acad_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.academic_calendar')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_mgmt.department')),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.student_division_allotment')),
                ('st_uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admission.student_details')),
            ],
        ),
        migrations.CreateModel(
            name='student_Attendance_date',
            fields=[
                ('student_attd_date_id', models.AutoField(primary_key=True, serialize=False)),
                ('session_index', models.SmallIntegerField(null=True)),
                ('division', models.CharField(max_length=2)),
                ('attendance_date', models.DateField(null=True)),
                ('attendance_time', models.CharField(default=None, max_length=10)),
                ('absentees_count', models.SmallIntegerField(null=True)),
                ('batch_no', models.CharField(default='B0', max_length=2)),
                ('acad_cal_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.academic_calendar')),
                ('faculty_id', models.ForeignKey(db_column='employee_emp_id', on_delete=django.db.models.deletion.CASCADE, to='hr.employee_details', to_field='employee_emp_id')),
                ('scheme_details_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.scheme_details')),
            ],
        ),
        migrations.CreateModel(
            name='student_attendance',
            fields=[
                ('student_attd_id', models.AutoField(primary_key=True, serialize=False)),
                ('division', models.CharField(max_length=2)),
                ('status', models.CharField(max_length=170)),
                ('No_classes_attended', models.SmallIntegerField(default=0, null=True)),
                ('Percentage_of_attendance', models.FloatField(blank=True, null=True)),
                ('batch_no', models.CharField(default='B0', max_length=2)),
                ('acad_cal_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.academic_calendar')),
                ('faculty_id', models.ForeignKey(db_column='employee_emp_id', on_delete=django.db.models.deletion.CASCADE, to='hr.employee_details', to_field='employee_emp_id')),
                ('scheme_details_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.scheme_details')),
                ('st_uid', models.ForeignKey(db_column='st_uid', on_delete=django.db.models.deletion.CASCADE, to='admission.student_details', to_field='st_uid')),
            ],
        ),
        migrations.CreateModel(
            name='First_Year_Student_Course_Registration_Details',
            fields=[
                ('first_year_st_course_reg_id', models.AutoField(primary_key=True, serialize=False)),
                ('semester', models.SmallIntegerField(default=1)),
                ('first_year_cycle', models.CharField(max_length=10)),
                ('registration_status', models.CharField(default='R', max_length=2)),
                ('batch_no', models.CharField(default='B0', max_length=2)),
                ('acad_cal_id', models.ForeignKey(db_column='acad_cal_id', on_delete=django.db.models.deletion.CASCADE, to='academics.academic_calendar')),
                ('scheme_details_id', models.ForeignKey(db_column='scheme_details_id', on_delete=django.db.models.deletion.CASCADE, to='academics.scheme_details')),
                ('st_branch', models.ForeignKey(db_column='st_branch', on_delete=django.db.models.deletion.CASCADE, to='master_mgmt.department')),
                ('st_uid', models.ForeignKey(db_column='st_uid', on_delete=django.db.models.deletion.CASCADE, to='admission.student_details', to_field='st_uid')),
            ],
            options={
                'unique_together': {('acad_cal_id', 'st_uid', 'scheme_details_id')},
            },
        ),
        migrations.CreateModel(
            name='Faculty_Course_Allotment',
            fields=[
                ('faculty_course_id', models.AutoField(primary_key=True, serialize=False)),
                ('sem', models.SmallIntegerField(default=1)),
                ('session_count', models.SmallIntegerField(null=True)),
                ('batch_no', models.CharField(default='B0', max_length=2)),
                ('acad_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_mgmt.academicyear')),
                ('course_code', models.ForeignKey(db_column='course_code', default='11UCSC111', on_delete=django.db.models.deletion.CASCADE, to='academics.scheme_details', to_field='course_code')),
                ('division', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='master_mgmt.division')),
                ('employee_emp_id', models.ForeignKey(db_column='employee_emp_id', on_delete=django.db.models.deletion.CASCADE, to='hr.employee_details', to_field='employee_emp_id')),
            ],
            options={
                'unique_together': {('employee_emp_id', 'acad_year', 'sem', 'division', 'course_code', 'batch_no')},
            },
        ),
        migrations.CreateModel(
            name='Declare_Assessment',
            fields=[
                ('declare_assessment_id', models.AutoField(primary_key=True, serialize=False)),
                ('sem', models.SmallIntegerField()),
                ('assessment_type', models.CharField(max_length=10)),
                ('max_marks', models.SmallIntegerField(default=20)),
                ('ans_q', models.SmallIntegerField(null=True)),
                ('date', models.DateField()),
                ('acad_cal_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.academic_calendar')),
                ('scheme_details_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.scheme_details')),
            ],
            options={
                'unique_together': {('assessment_type', 'scheme_details_id', 'max_marks', 'acad_cal_id')},
            },
        ),
        migrations.CreateModel(
            name='Assessment_Pattern_Question',
            fields=[
                ('assessment_pattern_num_id', models.AutoField(primary_key=True, serialize=False)),
                ('qnum', models.SmallIntegerField(null=True)),
                ('is_compulsory', models.SmallIntegerField(default=0, null=True)),
                ('max_marks', models.SmallIntegerField(null=True)),
                ('declare_assessment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='academics.declare_assessment')),
            ],
            options={
                'unique_together': {('qnum', 'declare_assessment_id')},
            },
        ),
        migrations.CreateModel(
            name='Academics_Master_Details',
            fields=[
                ('academics_master_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('ia1_marks', models.SmallIntegerField(default=0)),
                ('ia2_marks', models.SmallIntegerField(default=0)),
                ('ia3_marks', models.SmallIntegerField(default=0)),
                ('cta_marks', models.SmallIntegerField(default=0)),
                ('cie_marks', models.SmallIntegerField(default=0)),
                ('cie_grade', models.CharField(default='F', max_length=1)),
                ('registration_status', models.CharField(default='0', max_length=1)),
                ('final_cie_eligibility_status', models.SmallIntegerField(default=0)),
                ('final_att_eligibility_status', models.SmallIntegerField(default=0)),
                ('No_classes_attended', models.ForeignKey(db_column='No_classes_attended', default=0, on_delete=django.db.models.deletion.CASCADE, to='academics.student_attendance')),
                ('acad_cal_id', models.ForeignKey(db_column='acad_cal_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='academics.academic_calendar')),
                ('classes_held', models.ForeignKey(db_column='classes_held', default=1, on_delete=django.db.models.deletion.CASCADE, to='academics.faculty_course_allotment')),
                ('division', models.ForeignKey(db_column='division', default=1, on_delete=django.db.models.deletion.CASCADE, to='academics.student_division_allotment')),
                ('scheme_details_id', models.ForeignKey(db_column='scheme_details_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='academics.scheme_details')),
                ('semester', models.ForeignKey(db_column='semester', on_delete=django.db.models.deletion.CASCADE, to='academics.first_year_student_course_registration_details')),
                ('st_branch_applied', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='master_mgmt.department')),
                ('st_uid', models.ForeignKey(db_column='st_uid', on_delete=django.db.models.deletion.CASCADE, to='admission.student_details', to_field='st_uid')),
            ],
        ),
        migrations.CreateModel(
            name='UG_Student_Division_Allotment',
            fields=[
                ('ug_div_allot_id', models.AutoField(primary_key=True, serialize=False)),
                ('acad_cal_id', models.ForeignKey(db_column='acad_cal_id', on_delete=django.db.models.deletion.CASCADE, to='academics.academic_calendar')),
                ('offered_by', models.ForeignKey(db_column='offered_by', on_delete=django.db.models.deletion.CASCADE, to='master_mgmt.department')),
                ('st_uid', models.ForeignKey(db_column='st_uid', on_delete=django.db.models.deletion.CASCADE, to='admission.student_details', to_field='st_uid')),
                ('ug_division', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='master_mgmt.division')),
            ],
            options={
                'unique_together': {('acad_cal_id', 'st_uid', 'offered_by')},
            },
        ),
        migrations.CreateModel(
            name='UG_Student_Course_Registration_Details',
            fields=[
                ('ug_st_course_id', models.AutoField(primary_key=True, serialize=False)),
                ('semester', models.SmallIntegerField()),
                ('registration_status', models.CharField(default='R', max_length=1)),
                ('batch_no', models.CharField(default='B0', max_length=2)),
                ('acad_cal_id', models.ForeignKey(db_column='acad_cal_id', on_delete=django.db.models.deletion.CASCADE, to='academics.academic_calendar')),
                ('scheme_details_id', models.ForeignKey(db_column='scheme_details_id', on_delete=django.db.models.deletion.CASCADE, to='academics.scheme_details')),
                ('st_branch', models.ForeignKey(db_column='st_branch', on_delete=django.db.models.deletion.CASCADE, to='master_mgmt.department')),
                ('st_uid', models.ForeignKey(db_column='st_uid', on_delete=django.db.models.deletion.CASCADE, to='admission.student_details', to_field='st_uid')),
            ],
            options={
                'unique_together': {('acad_cal_id', 'st_uid', 'scheme_details_id')},
            },
        ),
        migrations.CreateModel(
            name='Student_Promotion_List',
            fields=[
                ('st_promotion_id', models.AutoField(primary_key=True, serialize=False)),
                ('st_name', models.CharField(max_length=50, null=True)),
                ('acad_cal_id_even', models.ForeignKey(db_column='acad_cal_id_even', default=4, on_delete=django.db.models.deletion.CASCADE, related_name='even_sem_id', to='academics.academic_calendar')),
                ('acad_cal_id_odd', models.ForeignKey(db_column='acad_cal_id_odd', default=3, on_delete=django.db.models.deletion.CASCADE, related_name='odd_sem_id', to='academics.academic_calendar')),
                ('offered_by', models.ForeignKey(db_column='offered_by', on_delete=django.db.models.deletion.CASCADE, to='master_mgmt.department')),
                ('st_uid', models.ForeignKey(db_column='st_uid', on_delete=django.db.models.deletion.CASCADE, to='admission.student_details', to_field='st_uid')),
            ],
            options={
                'unique_together': {('acad_cal_id_odd', 'acad_cal_id_even', 'offered_by', 'st_uid')},
            },
        ),
        migrations.CreateModel(
            name='Scheme_Allotment',
            fields=[
                ('scheme_allotment_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_sem', models.SmallIntegerField()),
                ('scheme_series', models.SmallIntegerField()),
                ('acad_cal_id', models.ForeignKey(db_column='acad_cal_id', on_delete=django.db.models.deletion.CASCADE, to='academics.academic_calendar')),
            ],
            options={
                'unique_together': {('acad_cal_id', 'course_sem')},
            },
        ),
        migrations.CreateModel(
            name='First_Year_Course_Details',
            fields=[
                ('first_year_course_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_year_sem', models.SmallIntegerField()),
                ('first_year_cycle', models.CharField(max_length=10)),
                ('acad_cal_id', models.ForeignKey(db_column='acad_cal_id', on_delete=django.db.models.deletion.CASCADE, to='academics.academic_calendar')),
                ('scheme_details_id', models.ForeignKey(db_column='scheme_details_id', on_delete=django.db.models.deletion.CASCADE, to='academics.scheme_details')),
            ],
            options={
                'unique_together': {('scheme_details_id', 'first_year_cycle', 'acad_cal_id')},
            },
        ),
        migrations.CreateModel(
            name='Cycle_Division_allotment',
            fields=[
                ('cycle_div_allot_id', models.AutoField(primary_key=True, serialize=False)),
                ('sem', models.SmallIntegerField()),
                ('cycle', models.CharField(max_length=1)),
                ('div', models.CharField(max_length=1)),
                ('acad_cal_id', models.ForeignKey(db_column='acad_cal_id', on_delete=django.db.models.deletion.CASCADE, to='academics.academic_calendar')),
            ],
            options={
                'unique_together': {('acad_cal_id', 'div', 'sem')},
            },
        ),
        migrations.CreateModel(
            name='Course_Equivalence',
            fields=[
                ('course_equivalence_id', models.AutoField(primary_key=True, serialize=False)),
                ('old_course_code', models.CharField(max_length=10)),
                ('new_course_code', models.CharField(max_length=10)),
                ('new_scheme_details_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_scheme_details_id', to='academics.scheme_details')),
                ('old_scheme_details_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='old_scheme_details_id', to='academics.scheme_details')),
            ],
            options={
                'unique_together': {('old_course_code', 'new_course_code', 'old_scheme_details_id', 'new_scheme_details_id')},
            },
        ),
        migrations.CreateModel(
            name='BitWise_Marks',
            fields=[
                ('bitwise_marks_id', models.AutoField(primary_key=True, serialize=False)),
                ('qnum', models.SmallIntegerField()),
                ('subqnum', models.CharField(max_length=10)),
                ('obtained_marks', models.SmallIntegerField(default=0)),
                ('assessment_pattern_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessmentpattern', to='academics.assessment_pattern_question')),
                ('st_uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admission.student_details')),
            ],
            options={
                'unique_together': {('st_uid', 'qnum', 'subqnum', 'assessment_pattern_id')},
            },
        ),
        migrations.CreateModel(
            name='Assessment_Pattern_Sub_Question',
            fields=[
                ('assessment_pattern_sbqnum_id', models.AutoField(primary_key=True, serialize=False)),
                ('subqnum', models.CharField(max_length=1)),
                ('max_marks', models.SmallIntegerField(null=True)),
                ('assessment_pattern_qnum_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subquestion', to='academics.assessment_pattern_question')),
                ('co', models.ManyToManyField(to='academics.Course_Outcome')),
            ],
            options={
                'unique_together': {('assessment_pattern_qnum_id', 'subqnum')},
            },
        ),
    ]
