# Generated by Django 3.2.12 on 2024-07-25 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0001_initial'),
        ('master_mgmt', '0001_initial'),
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detained_Students',
            fields=[
                ('dt_st_id', models.AutoField(primary_key=True, serialize=False)),
                ('semester', models.SmallIntegerField(null=True)),
                ('acad_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_mgmt.academicyear')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_mgmt.department')),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_mgmt.division')),
                ('scheme_details_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.scheme_details')),
                ('st_uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admission.student_details')),
            ],
        ),
    ]
