# Generated by Django 3.2.12 on 2024-08-29 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_courseoutcomepo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseoutcome',
            name='co_description',
        ),
    ]
