# Generated by Django 3.2.12 on 2024-08-29 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0008_remove_courseoutcome_co_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseoutcomepo',
            name='co_description',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
