# Generated by Django 3.2.12 on 2024-09-13 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_mgmt', '0002_detained_type'),
        ('academics', '0009_courseoutcomepo_co_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='ug_student_course_registration_details',
            name='division',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='master_mgmt.division'),
        ),
    ]
