# Generated by Django 3.2.12 on 2024-09-13 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0011_auto_20240913_1233'),
       
    ]

    operations = [
        migrations.AddField(
            model_name='ug_student_course_registration_details',
            name='division',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='master_mgmt.division'),
        ),
    ]
