# Generated by Django 3.2.12 on 2024-09-18 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_mgmt', '0002_detained_type'),
        ('hr', '0001_initial'),
        ('academics', '0013_ug_student_course_registration_details_division'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty_course_allotment',
            name='acad_cal_type',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterUniqueTogether(
            name='faculty_course_allotment',
            unique_together={('employee_emp_id', 'acad_cal_type', 'acad_year', 'sem', 'division', 'course_code', 'batch_no')},
        ),
    ]
