# Generated by Django 3.2.12 on 2024-09-18 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0014_auto_20240918_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty_course_allotment',
            name='acad_cal_type',
            field=models.SmallIntegerField(default=1, null=True),
        ),
    ]
